// app/layout.tsx (or app/layout.js)
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Hono | nextjs",
  description: "Generated by hono",
};

// Make this function async!
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return await ClerkProvider({
    children: (
      <html lang="en">
        <body className="bg-gray-100">
          <Navbar />
          {children}
        </body>
      </html>
    ),
  });
}
