// app/layout.tsx (or app/layout.js)
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { auth } from "@/lib/auth";
import { Analytics } from "@vercel/analytics/next";

export const metadata: Metadata = {
  title: "Hono | nextjs",
  description: "Generated by hono",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Navbar session={session} />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
